# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'Stefano Cecere' # Website name
baseurl: 'https://cecere.xyz/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /about/**
    type: docs
    sidebar:
      open: true
    editable: false
    share: false
    show_breadcrumb: true
    reading_time: false
    hide_date: true
    show_date_updated: false
  - _target:
      path: /project/**
    show_related: true
  - _target:
      path: /event/**
    show_related: true
  - _target:
      path: /played/**
    show_breadcrumb: true
    show_related: true
    editable: true
  - _target:
      path: /studio/**
    show_breadcrumb: true
    show_related: false
    editable: true
  # Blog post options
  - _target:
      path: /post/**
      kind: page
    view: date-title-summary
    authors:
      - stefano
    pager: true
    editable: false
    hide_date: false
    show_date_updated: false
    reading_time: true
    commentable: false
    show_related: true
    share: false
    show_breadcrumb: true
    paginate: 200
    header:
      navbar:
        enable: true

############################
## LANGUAGE
############################

defaultContentLanguage: it
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: false
enableGitInfo: false
summaryLength: 30
paginate: 100
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  post: '/post/:slug/'
  event: '/event/:year/:slug/'
  played: '/:sections/:slug'
  project: '/project/:slug/'
  tags: '/tag/:slug/'
  categories: '/c/:slug/'
disableAliases: false
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 95
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  goldmark:
    parser:
      attribute:
        block: true
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

ignoreLogs:
  - 'err-youtube-remote'
  