# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: ''
    weight: 10
  - name: Candidatura in EU
    url: '/play'
    weight: 15
#  - name: Now
#    url: '/now'
#    weight: 15
  - name: Blog
    url: '/post'
    weight: 20
#  - name: Tags
#    url: '/tags'
#    weight: 25
  - name: Progetti
    url: '/project'
    weight: 30    
  - name: Talks
    url: '/event'
    weight: 40
#  - name: "2042ᵉᵈ"
#    url: 'https://2042ed.org/'
#    weight: 50
#  - name: "2050ˣ"
#    url: 'https://2050x.org/'
#    weight: 95
#  - name: "Newsletter"
#    url: 'https://2042.substack.com'
#    weight: 100
  - name: Chi sono
    url: '/about'
    weight: 200
  - name: Contact
    url: '/contact'
    weight: 900

# sidebar:
#   - identifier: more
#     name: Still need help?
#     params:
#       type: separator
#     weight: 1
#   - identifier: community
#     name: "Community"
#     pageRef: "/community"
#     weight: 2
#   - identifier: hugoDocs
#     name: "Hugo Docs ↗"
#     url: "https://docs.hugoblox.com"
#     weight: 3

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70

#    identifier: main
#  - name: PlayED
#    url: '/played'
#    weight: 70
#    parent: main
#  - name: "2042+"
#    url: '/2042'
#    weight: 90
#    parent: main
#  - name: Jamurr
#    url: '/jamurr'
#    weight: 80
#    parent: main
#  - name: Progetti
#    url: '/projects'
#    weight: 60
#    parent: main
