# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Eventi
    url: '/events'
    weight: 30
  - name: Blog
    url: '/post'
    weight: 15
  - name: Scuola
    url: '/edu'
    weight: 20
  - name: PlayED
    url: '/played'
    weight: 40
  - name: "2042+"
    url: '/2042'
    weight: 42
  - name: Jamurr
    url: '/jamurr'
    weight: 42
  - name: Progetti
    url: '/projects'
    weight: 45
  - name: Chi sono
    url: '/about'
    weight: 90
  - name: Contatto
    url: '/contact'
    weight: 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
