# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Now"
  url = "/now"
  weight = 17

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 20

[[main]]
  name = "Ludosofia"
  url = "/ludosofia"
  weight = 25

[[main]]
  name = "Studio"
  url = "/studio"
  weight = 30

[[main]]
  name = "Projects"
  url = "/project"
  weight = 35


[[main]]
  name = "Educator"
  url = "/educator"
  weight = 37

[[main]]
  name = "Talks"
  url = "/talk"
  weight = 40


[[main]]
  name = "About"
  url = "/about"
  weight = 60

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
