# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Now
    url: 'now'
    weight: 17
  - name: Blog
    url: '/blog'
    weight: 20
  - name: Ludosofia
    url: '/ludosofia'
    weight: 25
  - name: Studio
    url: '/studio'
    weight: 30
  - name: Projects
    url: '/projects'
    weight: 35
  - name: Educator
    url: '/educator'
    weight: 37
  - name: Talks
    url: '/talks'
    weight: 40
  - name: About
    url: '/about'
    weight: 60
  - name: Contact
    url: '/contact'
    weight: 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
