# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: ''
    weight: 10
  - name: Blog
    url: '/post'
    weight: 20
  - name: Talks
    url: '/events'
    weight: 30
  - name: Corsi
    url: '/edu'
    weight: 40
  - name: Progetti
    url: '/projects'
    weight: 50
  - name: Studio
    url: '/studio'
    weight: 95
  - name: Chi sono
    url: '/about'
    weight: 100
  - name: Contatto
    url: '/contact'
    weight: 900

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70

#    identifier: main
#  - name: PlayED
#    url: '/played'
#    weight: 70
#    parent: main
#  - name: "2042+"
#    url: '/2042'
#    weight: 90
#    parent: main
#  - name: Jamurr
#    url: '/jamurr'
#    weight: 80
#    parent: main
#  - name: Progetti
#    url: '/projects'
#    weight: 60
#    parent: main
