# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'very serious research and play.'
    twitter: 'StefanoCecere'
  analytics:
    google_analytics: 'UA-95775-1'
    google_tag_manager: 'G-EVD3BV59KL'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Stefano Cecere"
      # Logo filename in `assets/media/` folder
      filename: "icon.png"
#    button:
#      enable: true
#      text: "Get Started"
#      url: "https://hugoblox.com/templates/"
    show_search: false
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Stefano Cecere. {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2 Jan 2006'
  time_format: '15:04'
  address_format: fr-fr

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/StefanoCecere/cecere.xyz'
    content_dir: 
    branch: main
